name: "dotenv Seeder"
description: "A GitHub Action to seed environment variables in a .env file using sed."
author: "scrlkx"
inputs:
  target:
    description: "The target .env file to update (e.g., .env)"
    required: false
    default: ".env"
  example:
    description: "The example .env file to copy from (e.g., .env.example)"
    required: false
    default: ".env.example"
  variables:
    description: "JSON object of variables to replace in the .env file"
    required: true
runs:
  using: "node20"
  main: index.js
