name: "dotenv Seeder"
description: "Seeds environment variables into a env file using JSON input."
author: "scrlkx <me@scrlkx.com>"

inputs:
  target:
    description: "The target environment file to update (e.g., .env)"
    required: false
    default: ".env"
  example:
    description: "The example environment file to copy from (e.g., .env.example)"
    required: false
    default: ".env.example"
  variables:
    description: "JSON object of variables to replace in the environment file"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
